package course;

public class _009BoxingUnboxingWrapperClasses {

	public static void main(String[] args) {

		int x = 20;
		
		Object obj = x; // BOXING - CONVERTEU UMA VARIÁVEL TIPO VALOR PARA UM OBJETO TIPO REFERÊNCIA!
		// O VALOR IRA PASSAR PARA O HEAP
		
		int y = (int) obj; // UNBOXING - FEZ O CONTRARIO
		
		// NOTE QUE PRECISOU FAZER UM CASTING PARA CONVERTER O VALOR DO OBJETO PARA INTEIRO, PARA ISSO EXISTEM AS WRAPPER CLASSES (ABAIXO)
		
		// WRAPPER CLASSES - SAO CLASSES EQUIVALENTES AOS TIPOS PRIMITIVOS. É USADO PARA FAZER BOXING E UNBOXING DE FORMA NATURAL NA LINGUAGEM!
		
		Integer obj1 = 10;
		
		int z = obj1 * 2; // NÃO PRECISOU FAZER O CASTING!
		
		System.out.println(y);
		System.out.println(z);
		
		// UMA VANTAGEM IMPORTANTE DO WRAPPER CLASS É ACEITAR O VALOR NULO! TIPO PRIMITIVO NÃO ACEITA. ISSO É IMPORTANTE EM PREENCHIMENTO DE CAMPO DE ENTIDADES
		// POR EXEMPLO, SE FOR OPCIONAL PREENCHER SUA DATA DE NASCIMENTO, SE DEIXAR EM BRANCO TERA O VALOR NULO QUE SÓ É POSSÍVEL COM O WRAPPER CLASSES!

	}

}
